-- Populating all property columns for CLAIMS


SELECT CFXML_ID, CLAIM_NODE_ID, ROOTID, PARENTID, PARENTTYPE, KIND, TYPE,
MAX(STATUSCHANGEDATETIME) AS  STATUSCHANGEDATETIME,
MAX(INCIDENTTYPEDESCRIPTION) AS  INCIDENTTYPEDESCRIPTION,
MAX(INTERNALCLAIMTYPEDESCRIPTION) AS  INTERNALCLAIMTYPEDESCRIPTION,
MAX(POLICYPRODUCTDESCRIPTION) AS  POLICYPRODUCTDESCRIPTION,
MAX(POLICYEXISTSINDICATOR) AS  POLICYEXISTSINDICATOR,
MAX(RESERVEEXISTSINDICATOR) AS  RESERVEEXISTSINDICATOR,
MAX(SENSITIVECLAIMINDICATOR) AS  SENSITIVECLAIMINDICATOR,
MAX(AUTOMATEDFNOLCLAIMINDICATOR) AS  AUTOMATEDFNOLCLAIMINDICATOR,
MAX(FNOLSUCCESSFULFIRSTATTEMPTINDICATOR) AS  FNOLSUCCESSFULFIRSTATTEMPTINDICATOR,
MAX(HOUSECOUNSELACCESSINDICATOR) AS  HOUSECOUNSELACCESSINDICATOR,
MAX(FIRSTREPORTOFINJURYFILEDINDICATOR) AS  FIRSTREPORTOFINJURYFILEDINDICATOR,
MAX(DIRECTINPUTCLAIMCREATIONINDICATOR) AS  DIRECTINPUTCLAIMCREATIONINDICATOR,
MAX(NCCIDCICLAIMINDICATOR) AS  NCCIDCICLAIMINDICATOR,
MAX(CLOSEDBYCLAIMMAINDESKINDICATOR) AS  CLOSEDBYCLAIMMAINDESKINDICATOR,
MAX(SPECIALACCOUNTINDICATOR) AS  SPECIALACCOUNTINDICATOR,
MAX(INITIALCLOSEDDATETIME) AS  INITIALCLOSEDDATETIME,
MAX(EDIACTIVEINDICATOR) AS  EDIACTIVEINDICATOR,
MAX(REINSURANCEIDENTIFIEDINDICATOR) AS  REINSURANCEIDENTIFIEDINDICATOR,
MAX(TREATYREINSURANCEINDICATOR) AS  TREATYREINSURANCEINDICATOR,
MAX(FACULTATIVEREINSURANCEINDICATOR) AS  FACULTATIVEREINSURANCEINDICATOR,
MAX(ARCHIVESTATUSDESCRIPTION) AS  ARCHIVESTATUSDESCRIPTION,
MAX(PAPERCLAIMCONVERSIONINDICATOR) AS  PAPERCLAIMCONVERSIONINDICATOR,
MAX(OCCURRENCEQUANTITY) AS  OCCURRENCEQUANTITY,
MAX(COVERAGEREFERRALINDICATOR) AS  COVERAGEREFERRALINDICATOR,
MAX(COMPANYCODEANDFULLPOLICYNUMBER) AS  COMPANYCODEANDFULLPOLICYNUMBER,
MAX(COMPANYCODEANDPOLICYSYMBOL) AS  COMPANYCODEANDPOLICYSYMBOL,
MAX(CONTRACTVERSIONENDDATETIME) AS  CONTRACTVERSIONENDDATETIME,
MAX(CONTRACTVERSIONSTARTDATETIME) AS  CONTRACTVERSIONSTARTDATETIME,
MAX(LARGELOSSINDICATOR) AS  LARGELOSSINDICATOR,
MAX(LASTCHANGEDDATETIME) AS  LASTCHANGEDDATETIME,
MAX(LASTCHANGEDUSERNAME) AS  LASTCHANGEDUSERNAME,
MAX(POLICYCOMPANYNUMBER) AS  POLICYCOMPANYNUMBER,
MAX(POLICYEFFECTIVEDATE) AS  POLICYEFFECTIVEDATE,
MAX(POLICYEXPIRATIONDATE) AS  POLICYEXPIRATIONDATE,
MAX(POLICYIDENTIFIER) AS  POLICYIDENTIFIER,
MAX(POLICYMODULENUMBER) AS  POLICYMODULENUMBER,
MAX(SENSITIVEPOLICYINDICATOR) AS  SENSITIVEPOLICYINDICATOR,
MAX(SOURCECOVERAGEIDENTIFIER) AS  SOURCECOVERAGEIDENTIFIER,
MAX(SOURCECOVERAGEDESCRIPTION) AS  SOURCECOVERAGEDESCRIPTION,
MAX(CLASSCODE) AS  CLASSCODE,
MAX(COVERAGEEFFECTIVEDATE) AS  COVERAGEEFFECTIVEDATE,
MAX(COVERAGEEXPIRATIONDATE) AS  COVERAGEEXPIRATIONDATE,
MAX(SERIALNUMBER) AS  SERIALNUMBER,
MAX(UNITIDENTIFIER) AS  UNITIDENTIFIER,
MAX(UNIQUECOVERAGEIDENTIFIER) AS  UNIQUECOVERAGEIDENTIFIER,
MAX(BUREAUTYPECODE) AS  BUREAUTYPECODE,
MAX(MAJORPERILCODE) AS  MAJORPERILCODE,
MAX(MAJORPERILSEQUENCENUMBER) AS  MAJORPERILSEQUENCENUMBER,
MAX(SERIESIIREFORMATTEDRECORDCODE) AS  SERIESIIREFORMATTEDRECORDCODE,
MAX(STATISTICALSTATECODE) AS  STATISTICALSTATECODE,
MAX(STATISTICALSUBLINECODE) AS  STATISTICALSUBLINECODE,
MAX(BUILDINGNUMBER) AS  BUILDINGNUMBER,
MAX(ADJUSTERCOVERAGEDESCRIPTION) AS  ADJUSTERCOVERAGEDESCRIPTION,
MAX(SUBCLAIMNUMBER) AS  SUBCLAIMNUMBER,
MAX(CREATEDDATETIME) AS  CREATEDDATETIME,
MAX(CREATORUSERNAME) AS  CREATORUSERNAME,
MAX(SALVAGESTATUSDESCRIPTION) AS  SALVAGESTATUSDESCRIPTION,
MAX(OTHERINSURANCEINDICATOR) AS  OTHERINSURANCEINDICATOR,
MAX(SUBROGATIONSTATUSDESCRIPTION) AS  SUBROGATIONSTATUSDESCRIPTION,
MAX(LITIGATIONINDICATOR) AS  LITIGATIONINDICATOR,
MAX(NEGOTIATIONINDICATOR) AS  NEGOTIATIONINDICATOR,
MAX(SIUREVIEWINDICATOR) AS  SIUREVIEWINDICATOR,
MAX(SUBCLAIMCOVERAGECONFIRMEDINDICATOR) AS  SUBCLAIMCOVERAGECONFIRMEDINDICATOR,
MAX(DIRECTINPUTSUBCLAIMCREATIONINDICATOR) AS  DIRECTINPUTSUBCLAIMCREATIONINDICATOR,
MAX(GLASSINDICATOR) AS  GLASSINDICATOR,
MAX(DEDUCTIBLERECOVERYINDICATOR) AS  DEDUCTIBLERECOVERYINDICATOR,
MAX(CAUSEOFLOSSCODE) AS  CAUSEOFLOSSCODE,
MAX(CAUSEOFLOSSDESCRIPTION) AS  CAUSEOFLOSSDESCRIPTION
FROM
(
 SELECT CFXML_ID,rootid, parentid , parenttype, kind, type,  ID AS CLAIM_NODE_ID, 
 CASE WHEN PROP_EXPLOD.KIND='claimNumber' THEN PROP_EXPLOD.CONTENT ELSE NULL END AS CLAIMNUMBER,
 CASE WHEN PROP_EXPLOD.KIND='createdDatetime' THEN PROP_EXPLOD.CONTENT ELSE NULL END AS createdDatetime,
 CASE WHEN PROP_EXPLOD.KIND='statusDescription' THEN PROP_EXPLOD.CONTENT ELSE NULL END AS statusDescription,
 CASE WHEN PROP_EXPLOD.KIND='statusChangeDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS  STATUSCHANGEDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='incidentTypeDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   INCIDENTTYPEDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='internalClaimTypeDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   INTERNALCLAIMTYPEDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='policyProductDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYPRODUCTDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='policyExistsIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYEXISTSINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='reserveExistsIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   RESERVEEXISTSINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='sensitiveClaimIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SENSITIVECLAIMINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='automatedFNOLClaimIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   AUTOMATEDFNOLCLAIMINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='fnolSuccessfulFirstAttemptIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   FNOLSUCCESSFULFIRSTATTEMPTINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='houseCounselAccessIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   HOUSECOUNSELACCESSINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='firstReportOfInjuryFiledIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   FIRSTREPORTOFINJURYFILEDINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='directInputClaimCreationIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   DIRECTINPUTCLAIMCREATIONINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='ncciDCIClaimIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   NCCIDCICLAIMINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='closedByClaimMainDeskIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CLOSEDBYCLAIMMAINDESKINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='specialAccountIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SPECIALACCOUNTINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='initialClosedDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   INITIALCLOSEDDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='ediActiveIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   EDIACTIVEINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='reinsuranceIdentifiedIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   REINSURANCEIDENTIFIEDINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='treatyReinsuranceIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   TREATYREINSURANCEINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='facultativeReinsuranceIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   FACULTATIVEREINSURANCEINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='archiveStatusDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   ARCHIVESTATUSDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='paperClaimConversionIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   PAPERCLAIMCONVERSIONINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='occurrenceQuantity'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   OCCURRENCEQUANTITY,
 CASE WHEN PROP_EXPLOD.KIND='coverageReferralIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   COVERAGEREFERRALINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='companyCodeAndFullPolicyNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   COMPANYCODEANDFULLPOLICYNUMBER,
 CASE WHEN PROP_EXPLOD.KIND='companyCodeAndPolicySymbol'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   COMPANYCODEANDPOLICYSYMBOL,
 CASE WHEN PROP_EXPLOD.KIND='contractVersionEndDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CONTRACTVERSIONENDDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='contractVersionStartDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CONTRACTVERSIONSTARTDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='largeLossIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   LARGELOSSINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='lastChangedDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   LASTCHANGEDDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='lastChangedUsername'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   LASTCHANGEDUSERNAME,
 CASE WHEN PROP_EXPLOD.KIND='policyCompanyNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYCOMPANYNUMBER,
 CASE WHEN PROP_EXPLOD.KIND='policyEffectiveDate'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYEFFECTIVEDATE,
 CASE WHEN PROP_EXPLOD.KIND='policyExpirationDate'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYEXPIRATIONDATE,
 CASE WHEN PROP_EXPLOD.KIND='policyIdentifier'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYIDENTIFIER,
 CASE WHEN PROP_EXPLOD.KIND='policyModuleNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   POLICYMODULENUMBER,
 CASE WHEN PROP_EXPLOD.KIND='sensitivePolicyIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SENSITIVEPOLICYINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='sourceCoverageIdentifier'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SOURCECOVERAGEIDENTIFIER,
 CASE WHEN PROP_EXPLOD.KIND='sourceCoverageDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SOURCECOVERAGEDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='classCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CLASSCODE,
 CASE WHEN PROP_EXPLOD.KIND='coverageEffectiveDate'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   COVERAGEEFFECTIVEDATE,
 CASE WHEN PROP_EXPLOD.KIND='coverageExpirationDate'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   COVERAGEEXPIRATIONDATE,
 CASE WHEN PROP_EXPLOD.KIND='serialNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SERIALNUMBER,
 CASE WHEN PROP_EXPLOD.KIND='unitIdentifier'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   UNITIDENTIFIER,
 CASE WHEN PROP_EXPLOD.KIND='uniqueCoverageIdentifier'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   UNIQUECOVERAGEIDENTIFIER,
 CASE WHEN PROP_EXPLOD.KIND='bureauTypeCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   BUREAUTYPECODE,
 CASE WHEN PROP_EXPLOD.KIND='majorPerilCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   MAJORPERILCODE,
 CASE WHEN PROP_EXPLOD.KIND='majorPerilSequenceNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   MAJORPERILSEQUENCENUMBER,
 CASE WHEN PROP_EXPLOD.KIND='seriesIIReformattedRecordCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SERIESIIREFORMATTEDRECORDCODE,
 CASE WHEN PROP_EXPLOD.KIND='statisticalStateCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   STATISTICALSTATECODE,
 CASE WHEN PROP_EXPLOD.KIND='statisticalSublineCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   STATISTICALSUBLINECODE,
 CASE WHEN PROP_EXPLOD.KIND='buildingNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   BUILDINGNUMBER,
 CASE WHEN PROP_EXPLOD.KIND='adjusterCoverageDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   ADJUSTERCOVERAGEDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='subclaimNumber'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SUBCLAIMNUMBER,
 --CASE WHEN PROP_EXPLOD.KIND='--statusDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --STATUSDESCRIPTION,
 --CASE WHEN PROP_EXPLOD.KIND='--statusChangeDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --STATUSCHANGEDATETIME,
 --CASE WHEN PROP_EXPLOD.KIND='createdDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CREATEDDATETIME,
 CASE WHEN PROP_EXPLOD.KIND='creatorUsername'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CREATORUSERNAME,
 --CASE WHEN PROP_EXPLOD.KIND='--lastChangedDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --LASTCHANGEDDATETIME,
 --CASE WHEN PROP_EXPLOD.KIND='--lastChangedUsername'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --LASTCHANGEDUSERNAME,
 --CASE WHEN PROP_EXPLOD.KIND='--sourceCoverageIdentifier'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --SOURCECOVERAGEIDENTIFIER,
 --CASE WHEN PROP_EXPLOD.KIND='--sourceCoverageDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --SOURCECOVERAGEDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='salvageStatusDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SALVAGESTATUSDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='otherInsuranceIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   OTHERINSURANCEINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='subrogationStatusDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SUBROGATIONSTATUSDESCRIPTION,
 CASE WHEN PROP_EXPLOD.KIND='litigationIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   LITIGATIONINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='negotiationIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   NEGOTIATIONINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='siuReviewIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SIUREVIEWINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='subclaimCoverageConfirmedIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   SUBCLAIMCOVERAGECONFIRMEDINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='directInputSubclaimCreationIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   DIRECTINPUTSUBCLAIMCREATIONINDICATOR,
 --CASE WHEN PROP_EXPLOD.KIND='--closedByClaimMainDeskIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --CLOSEDBYCLAIMMAINDESKINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='glassIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   GLASSINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='deductibleRecoveryIndicator'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   DEDUCTIBLERECOVERYINDICATOR,
 CASE WHEN PROP_EXPLOD.KIND='causeOfLossCode'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CAUSEOFLOSSCODE,
 CASE WHEN PROP_EXPLOD.KIND='causeOfLossDescription'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   CAUSEOFLOSSDESCRIPTION
 --CASE WHEN PROP_EXPLOD.KIND='--initialClosedDatetime'  THEN PROP_EXPLOD.CONTENT ELSE NULL END AS   --INITIALCLOSEDDATETIME,
  FROM
  (   
   SELECT CFXML_ID,CLM_EXPLOD.rootid, CLM_EXPLOD.parentid , CLM_EXPLOD.parenttype , CLM_EXPLOD.kind ,CLM_EXPLOD.type ,CLM_EXPLOD.id ,CLM_EXPLOD.PROPERTY AS PROP 
FROM
(
SELECT
   cfxml_1.id AS CFXML_ID ,cfxml_1.claim AS CLM
FROM cinfin_claims 
LATERAL VIEW explode(cfxml) exploded_table as cfxml_1
where cfxml_1.id='DE000565B5031EE5978D67E1CF6D50B2'
) TMP
LATERAL VIEW explode(CLM) exploded_table as CLM_EXPLOD
   ) TMP2
   LATERAL VIEW explode(PROP) exploded_table as PROP_EXPLOD
  ) TMP3  GROUP BY CFXML_ID, CLAIM_NODE_ID, ROOTID, PARENTID, PARENTTYPE, KIND, TYPE
   
   
   
   
   -- working fine
   
   
   
   -------------------===============================================================
   
   -- party /role
   
   
   SELECT ID,pe_id,CP.KIND,CP_PROP_EXPLOD.KIND, partyname_type,PN_PROP_EXPLOD.KIND,PD_TYPE,PD_PROP_EXPLOD.KIND
from
(SELECT ID,pe_id,CONTACTPOINT_EXPLOD.kind AS CP.KIND,CONTACTPOINT_EXPLOD.PROPERTY AS CP_PROP, PARTYNAME_EXPLOD.TYPE as partyname_type,PARTYNAME_EXPLOD.PROPERTY AS PN_PROP, PARTYDETAIL_EXPLOD.TYPE AS PD_TYPE,PARTYDETAIL_EXPLOD.PROPERTY AS PD_PROP
from
  (
   SELECT ID,PARTY_EXPLOD.ID as pe_id, PARTY_EXPLOD.CONTACTPOINT AS CONTCTPOINT, PARTY_EXPLOD.PARTYNAME AS PRTYNM, PARTY_EXPLOD.PARTYDETAIL AS PRTYDTL
FROM
(
SELECT ID,REF_EXPLOD,REF_EXPLOD.PARTY AS PARTY
FROM
(
SELECT
   cfxml_1.id AS ID , cfxml_1.references AS REF
FROM
   CINFIN_Claim_References
   LATERAL VIEW explode(cfxml) exploded_table as cfxml_1
   where cfxml_1.id='DE000565B5031EE5978D67E1CF6D50B2'
   ) TMP
   LATERAL VIEW explode(REF) exploded_table as REF_EXPLOD
   ) TMP2
   LATERAL VIEW explode(PARTY) exploded_table as PARTY_EXPLOD
) TMP3
LATERAL VIEW explode(CONTCTPOINT) exploded_table as CONTACTPOINT_EXPLOD
LATERAL VIEW explode(PRTYNM) exploded_table as PARTYNAME_EXPLOD
LATERAL VIEW explode(PRTYDTL)expolded_table as PARTYDETAIL_EXPLOD
) TMP4
 LATERAL VIEW explode(CP_PROP)expolded_table as CP_PROP_EXPLOD
 LATERAL VIEW explode(PN_PROP)expolded_table as PN_PROP_EXPLOD
 LATERAL VIEW explode(PD_PROP)expolded_table as PD_PROP_EXPLOD;
   
   
   