use policy_cinfin;
add jar json-serde-1.3-jar-with-dependencies.jar;
add jar hive-json-serde.jar;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_47883786.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_47883786.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_47883786.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_47883786.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_48034129.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_48034129.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_48034129.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_48034129.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49293188.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49293188.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49293188.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49293188.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49834863.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49834863.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49834863.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_49834863.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742690.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742690.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742690.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742690.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742820.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742820.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742820.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_52742820.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_53183415.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_53183415.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_53183415.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_53183415.001.json' into table CINFIN_Policy_FinancialProvisionDet;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_58860168.001.json' into table CINFIN_Policy_Role;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_58860168.001.json' into table CINFIN_Policy_References;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_58860168.001.json' into table CINFIN_Policy_FinancialProvision;
load data local inpath  '/home/ubuntu/cinfin/policy/outPOLICY_58860168.001.json' into table CINFIN_Policy_FinancialProvisionDet;
